apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: scart-order
spec:
  type: LoadBalancer
  ports:
  - port: 8090
  selector:
    app: scart-order
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: scart-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scart-order
  template:
    metadata:
      labels:
        app: scart-order
    spec:
      containers:
      - name: scart-order
        image: svaikund/scart-order:latest
        ports:
        - containerPort: 8090
