apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: scart-catalog
spec:
  type: NodePort
  ports:
  - port: 8087
  selector:
    app: scart-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: scart-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scart-catalog
  template:
    metadata:
      labels:
        app: scart-catalog
    spec:
      containers:
      - name: scart-catalog
        image: svaikund/scart-catalog:version1
        ports:
        - containerPort: 8087
