apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: scart-shipping
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: scart-shipping
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: scart-shipping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scart-shipping
  template:
    metadata:
      labels:
        app: scart-shipping
    spec:
      containers:
      - name: scart-shipping
        image: svaikund/scart-shipping:latest
        ports:
        - containerPort: 8080
